<a href="https://colab.research.google.com/github/vonnkee13/SortingArray/blob/main/Youtube_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
import pandas as pd
import time

In [2]:
API_KEY = 'AIzaSyCdXwOJWGgSYKrW9KTdo_XKKw5tZlfaWfE'
CHANNEL_ID = 'UCOoCLoWMQ4G_X5vIhR6Pzog'

In [5]:
#make API call
pageToken = ''
url = 'https://www.googleapis.com/youtube/v3/search?key='+API_KEY+'&channelId='+CHANNEL_ID+'&part=snippet,id&order=date&maxResults=1000'+pageToken
response = requests.get(url).json()

In [13]:
video_id=response['items'][0]['id']['videoId']

In [17]:
response['items'][0]['snippet']['title']

'5 Shihtzu Puppies 🐾'

In [22]:
upload_date=response['items'][0]['snippet']['publishedAt'].split('T')[0]

In [23]:
for video in response['items']:
  if video['id']['kind'] == 'youtube#video':
    video_id = video['id']['videoId']
    upload_date = video['snippet']['publishedAt'].split('T')[0]
    video_title = video['snippet']['title']

    print(video_id)
    print(video_title)
    print(upload_date)

h2TUum77eRk
5 Shihtzu Puppies 🐾
2021-08-01
cysLBFfSM1U
8 months 5 Shihtzu Puppies
2021-08-01
3LoklURSAsw
Tweedle ❤️
2021-05-11
iEt2uaPHskM
5 Shihtzu Puppies 🐾
2021-05-08
1Fm6s3nEgQI
5 Shihtzu puppies 🐾❤️
2021-04-10
TNQdyvSo3zI
5 Shihtzu Puppies 🐾 | 5 months old part 2
2021-04-08
QzCOCzv8Q-k
5 Shihtzu Puppies 🐾 | 5 months old 🙂
2021-04-08
IOe5lOXEJFU
Shihtzu watching Teletubbies part 2 | Tweedle the mama dog
2021-04-07
PtZKq7DCJtc
Shih tzu watching Teletubbies 😁😂 | Tweedle the Mama dog
2021-04-07
xZP2TRJW-Lo
Mama Dog (Tweedle) watching Billie Eilish
2021-03-17
wG0GPQHoY8A
Sleeping PAWtatoes ❤️😁
2021-03-11
YpWD9ZynWn4
They Grew Up so Fast 😁🥳
2021-02-28
CNF42Px3EsI
PAWtato 🐶😅
2021-02-25
6DKhp057g3I
5 Shihtzu Puppies 🐾 | Bagong Ligo 🧽😎🐶😁
2021-02-25
cmVRniJ3XCk
Happy 3rd Birthday Tweedle 🎉 | ft. Boiled Chicken | Tweedle the Mama/Nanay Shitzu Dog |
2021-02-03
jrXxYVP6UH0
5 Shihtzu Puppies 🐾 | 86 days old (part 2)
2021-02-03
Ztti6dnZXPk
5 Shihtzu Puppies 🐾 | 86 days old
2021-02-03
6Gq6wWb7GU4
5 Shihtzu Puppies 🐾 | Eating Strawberries 🍓
2021-01-28
N7mV8bG0Zfo
5 Shihtzu Puppies 🐾 | Enjoying Dog Snacks that I Ordered Online
2021-01-22
114hdHiGI5Q
5 Shihtzu Puppies 🐾 | 73 days old (part 2)
2021-01-20
t9O35wK5_nA
5 Shihtzu Puppies 🐾 | 73 days old
2021-01-20
SphRcIsWMLU
5 Shihtzu Puppies 🐾| Taking Coatshine Syrup | Omega Fatty Acids + Vitamins + Minerals
2021-01-20
WHSjAd_titk
Shihtzu 🐾 | Tweedle the Mama/Nanay Dog is Eating Dog snack
2021-01-18
XDM6odwAj1k
5 Shihtzu Puppies 🐾 | 5th Visit to the Veterinary | 6in1 Vaccination | 10 Weeks Old
2021-01-17
uzUbZpndzPM
5 Shihtzu Puppies 🐾😁 | ft. Human Size Teddy Bear Stuff Toy
2021-01-15
WpPZDUPyt5E
5 Shihtzu Puppies 🐾❤️ | Eating Banana 🍌 (part 2)
2021-01-15
vyuIOw84KsI
5 Shihtzu Puppies 🐾❤️ | Eating Banana 🍌
2021-01-15
tIhQyFUO1R8
Shihtzu Puppies 🐾😁 | 67 days old (part 2)
2021-01-14
mdllH634jiU
Shihtzu Puppies 🐾 😁 | 67 days old
2021-01-14
r2ZlOEYohRA
Shihtzu | Tweedle the Mama Dog ❤️🐾
2021-01-10
9xiaBnLBePs
Shih tzu Puppy 🐾 | Mickey is Playing Toy Eggs ❤️
2021-01-08
4RMi8hamiQA
2 Months old Shihtzu Puppies ♥️
2021-01-07
6mSTkyEIXIw
5 Shihtzu Puppies | 2 Months Old
2021-01-07
MkGQ3_jea-M
5 Shihtzu Puppies taking Multivitamins
2021-01-07
xiq8FlVj5Bk
I have 2 Pups, the left and the right 😁
2021-01-06
GUekoXvUMHo
Mickey wants to play with Goofy | Shihtzu puppies
2021-01-05
kyT9BaeSIYo
Shihtzu Puppies 🐾 |  Extra Large Rawhide for their Tiny Teeth
2021-01-05
gvy6Flwx0og
Shih tzu puppies 🐾 | 58 days old
2021-01-04
VYF7yAappZ4
Very Tender Marinade for Barbecue BBQ
2021-01-03
jD2A0Q3Eb0Y
Shih tzu puppies 🐾 | 57 days old (part 3)
2021-01-03
aEHaBPUdDZo
Shih tzu puppies 🐾 | 57 days old (part 2)
2021-01-03
XbPmRDPEBz0
Shih tzu puppies 🐾 | 57 days old
2021-01-03
qfb9VZBtClA
Loaf bread PIZZA cooked in a PAN ft. pineapple tidbits
2021-01-02
t3vkh04S8mg
Lechon Kawali | New Year Eve Edition
2021-01-02
1ezCEfREGxM
Pretty Tiny Teeth of a Shihtzu Puppy 🐾
2020-12-30
H-iN_ws1QkI
Tiny Barks of Shih tzu puppy | Dewey the 4th puppy
2020-12-30
EDe5qNIz8zI
Shih tzu puppies 🐾 | 53 days old
2020-12-30
nm8U8b2yTe0
How to cut your Shih tzu finger nails using regular nail clipper
2020-12-30
Splzs_mK1D4
Nissin | Aka Tonkotsu Flavour | Demae Ramen 🍜 with Soft boiled Egg 🥚 #nissin
2020-12-30
Atl8ZoDmsuY
Samyang Carbonara with extras | Bacon 🥓 , Soft boiled egg 🥚, Fish cakes #samyang #instantnoodles
2020-12-30

In [24]:
url_video_stats = 'https://www.googleapis.com/youtube/v3/videos?id='+video_id+'&part=statistics&key='+API_KEY
response_video_stats = requests.get(url_video_stats).json()

In [25]:
response_video_stats

{'etag': 'Ti5-FBq1CiixysJfjhxo5ovJres',
 'items': [{'etag': '_20d8dxzXCLgOxCGmYDSY_PcyPg',
   'id': 'Atl8ZoDmsuY',
   'kind': 'youtube#video',
   'statistics': {'commentCount': '1',
    'favoriteCount': '0',
    'likeCount': '93',
    'viewCount': '3144'}}],
 'kind': 'youtube#videoListResponse',
 'pageInfo': {'resultsPerPage': 1, 'totalResults': 1}}

In [27]:
for video in response['items']:
  if video['id']['kind'] == 'youtube#video':
    video_id = video['id']['videoId']
    upload_date = video['snippet']['publishedAt'].split('T')[0]
    video_title = video['snippet']['title']

    print(video_id)
    print(video_title)
    print(upload_date)

    #collecting views, likes, dislikes
    url_video_stats = 'https://www.googleapis.com/youtube/v3/videos?id='+video_id+'&part=statistics&key='+API_KEY
    response_video_stats = requests.get(url_video_stats).json()

    view_count = response_video_stats['items'][0]['statistics']['viewCount']
    like_count = response_video_stats['items'][0]['statistics']['likeCount']
    comment_count = response_video_stats['items'][0]['statistics']['commentCount']

h2TUum77eRk
5 Shihtzu Puppies 🐾
2021-08-01
978
38
3
cysLBFfSM1U
8 months 5 Shihtzu Puppies
2021-08-01
656
18
0
3LoklURSAsw
Tweedle ❤️
2021-05-11
4329
206
4
iEt2uaPHskM
5 Shihtzu Puppies 🐾
2021-05-08
887
42
2
1Fm6s3nEgQI
5 Shihtzu puppies 🐾❤️
2021-04-10
886
56
6
TNQdyvSo3zI
5 Shihtzu Puppies 🐾 | 5 months old part 2
2021-04-08
650
33
1
QzCOCzv8Q-k
5 Shihtzu Puppies 🐾 | 5 months old 🙂
2021-04-08
778
33
1
IOe5lOXEJFU
Shihtzu watching Teletubbies part 2 | Tweedle the mama dog
2021-04-07
136
13
0
PtZKq7DCJtc
Shih tzu watching Teletubbies 😁😂 | Tweedle the Mama dog
2021-04-07
161
15
2
xZP2TRJW-Lo
Mama Dog (Tweedle) watching Billie Eilish
2021-03-17
699
53
0
wG0GPQHoY8A
Sleeping PAWtatoes ❤️😁
2021-03-11
477
27
1
YpWD9ZynWn4
They Grew Up so Fast 😁🥳
2021-02-28
717
27
1
CNF42Px3EsI
PAWtato 🐶😅
2021-02-25
1563
59
2
6DKhp057g3I
5 Shihtzu Puppies 🐾 | Bagong Ligo 🧽😎🐶😁
2021-02-25
262
15
5
cmVRniJ3XCk
Happy 3rd Birthday Tweedle 🎉 | ft. Boiled Chicken | Tweedle the Mama/Nanay Shitzu Dog |
2021-02-03
1205
42
6
jrXxYVP6UH0
5 Shihtzu Puppies 🐾 | 86 days old (part 2)
2021-02-03
341
22
3
Ztti6dnZXPk
5 Shihtzu Puppies 🐾 | 86 days old
2021-02-03
800
28
4
6Gq6wWb7GU4
5 Shihtzu Puppies 🐾 | Eating Strawberries 🍓
2021-01-28
387
22
5
N7mV8bG0Zfo
5 Shihtzu Puppies 🐾 | Enjoying Dog Snacks that I Ordered Online
2021-01-22
316
15
5
114hdHiGI5Q
5 Shihtzu Puppies 🐾 | 73 days old (part 2)
2021-01-20
2086
82
6
t9O35wK5_nA
5 Shihtzu Puppies 🐾 | 73 days old
2021-01-20
1084
47
6
SphRcIsWMLU
5 Shihtzu Puppies 🐾| Taking Coatshine Syrup | Omega Fatty Acids + Vitamins + Minerals
2021-01-20
13762
71
25
WHSjAd_titk
Shihtzu 🐾 | Tweedle the Mama/Nanay Dog is Eating Dog snack
2021-01-18
364
26
2
XDM6odwAj1k
5 Shihtzu Puppies 🐾 | 5th Visit to the Veterinary | 6in1 Vaccination | 10 Weeks Old
2021-01-17
796
21
6
uzUbZpndzPM
5 Shihtzu Puppies 🐾😁 | ft. Human Size Teddy Bear Stuff Toy
2021-01-15
35677
1315
28
WpPZDUPyt5E
5 Shihtzu Puppies 🐾❤️ | Eating Banana 🍌 (part 2)
2021-01-15
243
16
3
vyuIOw84KsI
5 Shihtzu Puppies 🐾❤️ | Eating Banana 🍌
2021-01-15
471
17
3
tIhQyFUO1R8
Shihtzu Puppies 🐾😁 | 67 days old (part 2)
2021-01-14
217
12
3
mdllH634jiU
Shihtzu Puppies 🐾 😁 | 67 days old
2021-01-14
323
21
1
r2ZlOEYohRA
Shihtzu | Tweedle the Mama Dog ❤️🐾
2021-01-10
1757
74
6
9xiaBnLBePs
Shih tzu Puppy 🐾 | Mickey is Playing Toy Eggs ❤️
2021-01-08
252
14
3
4RMi8hamiQA
2 Months old Shihtzu Puppies ♥️
2021-01-07
3960
179
7
6mSTkyEIXIw
5 Shihtzu Puppies | 2 Months Old
2021-01-07
461
28
6
MkGQ3_jea-M
5 Shihtzu Puppies taking Multivitamins
2021-01-07
991
27
2
xiq8FlVj5Bk
I have 2 Pups, the left and the right 😁
2021-01-06
139
15
1
GUekoXvUMHo
Mickey wants to play with Goofy | Shihtzu puppies
2021-01-05
565
28
1
kyT9BaeSIYo
Shihtzu Puppies 🐾 |  Extra Large Rawhide for their Tiny Teeth
2021-01-05
1864
70
1
gvy6Flwx0og
Shih tzu puppies 🐾 | 58 days old
2021-01-04
3953
133
8
VYF7yAappZ4
Very Tender Marinade for Barbecue BBQ
2021-01-03
57
8
0
jD2A0Q3Eb0Y
Shih tzu puppies 🐾 | 57 days old (part 3)
2021-01-03
742
39
2
aEHaBPUdDZo
Shih tzu puppies 🐾 | 57 days old (part 2)
2021-01-03
1173
42
3
XbPmRDPEBz0
Shih tzu puppies 🐾 | 57 days old
2021-01-03
28122
753
19
qfb9VZBtClA
Loaf bread PIZZA cooked in a PAN ft. pineapple tidbits
2021-01-02
63
7
0
t3vkh04S8mg
Lechon Kawali | New Year Eve Edition
2021-01-02
49
4
0
1ezCEfREGxM
Pretty Tiny Teeth of a Shihtzu Puppy 🐾
2020-12-30
3287
171
9
H-iN_ws1QkI
Tiny Barks of Shih tzu puppy | Dewey the 4th puppy
2020-12-30
1075
43
1
EDe5qNIz8zI
Shih tzu puppies 🐾 | 53 days old
2020-12-30
704
29
4
nm8U8b2yTe0
How to cut your Shih tzu finger nails using regular nail clipper
2020-12-30
2188
19
0
Splzs_mK1D4
Nissin | Aka Tonkotsu Flavour | Demae Ramen 🍜 with Soft boiled Egg 🥚 #nissin
2020-12-30
7971
189
3
Atl8ZoDmsuY
Samyang Carbonara with extras | Bacon 🥓 , Soft boiled egg 🥚, Fish cakes #samyang #instantnoodles
2020-12-30
3144
93
1

In [37]:
#build our dataframe

column_names = ['video_id','upload_date','video_title','view_count','like_count','comment_count']
df = pd.DataFrame(columns=column_names)

In [38]:
df

Empty DataFrame
Columns: [video_id, upload_date, video_title, view_count, like_count, comment_count]
Index: []

In [39]:
for video in response['items']:
  if video['id']['kind'] == 'youtube#video':
    video_id = video['id']['videoId']
    upload_date = video['snippet']['publishedAt'].split('T')[0]
    video_title = video['snippet']['title']

    #collecting views, likes, dislikes
    url_video_stats = 'https://www.googleapis.com/youtube/v3/videos?id='+video_id+'&part=statistics&key='+API_KEY
    response_video_stats = requests.get(url_video_stats).json()

    view_count = response_video_stats['items'][0]['statistics']['viewCount']
    like_count = response_video_stats['items'][0]['statistics']['likeCount']
    comment_count = response_video_stats['items'][0]['statistics']['commentCount']

    #save data in pandas dataframe

    df = df.append({
        'video_id': video_id, 'upload_date': upload_date, 'video_title': video_title, 'view_count':view_count, 'like_count':like_count, 'comment_count':comment_count
    },ignore_index=True)

In [40]:
df

,video_id,upload_date,video_title,view_count,like_count,comment_count
0,h2TUum77eRk,2021-08-01,5 Shihtzu Puppies 🐾,978,38,3
1,cysLBFfSM1U,2021-08-01,8 months 5 Shihtzu Puppies,656,18,0
2,3LoklURSAsw,2021-05-11,Tweedle ❤️,4329,206,4
3,iEt2uaPHskM,2021-05-08,5 Shihtzu Puppies 🐾,887,42,2
4,1Fm6s3nEgQI,2021-04-10,5 Shihtzu puppies 🐾❤️,886,56,6
5,TNQdyvSo3zI,2021-04-08,5 Shihtzu Puppies 🐾 | 5 months old part 2,650,33,1
6,QzCOCzv8Q-k,2021-04-08,5 Shihtzu Puppies 🐾 | 5 months old 🙂,778,33,1
7,IOe5lOXEJFU,2021-04-07,Shihtzu watching Teletubbies part 2 | Tweedle ...,136,13,0
8,PtZKq7DCJtc,2021-04-07,Shih tzu watching Teletubbies 😁😂 | Tweedle the...,161,15,2
9,xZP2TRJW-Lo,2021-03-17,Mama Dog (Tweedle) watching Billie Eilish,699,53,0
10,wG0GPQHoY8A,2021-03-11,Sleeping PAWtatoes ❤️😁,477,27,1
11,YpWD9ZynWn4,2021-02-28,They Grew Up so Fast 😁🥳,717,27,1
12,CNF42Px3EsI,2021-02-25,PAWtato 🐶😅,1563,59,2
13,6DKhp057g3I,2021-02-25,5 Shihtzu Puppies 🐾 | Bagong Ligo 🧽😎🐶😁,262,15,5
14,cmVRniJ3XCk,2021-02-03,Happy 3rd Birthday Tweedle 🎉 | ft. Boiled Chic...,1205,42,6
15,jrXxYVP6UH0,2021-02-03,5 Shihtzu Puppies 🐾 | 86 days old (part 2),341,22,3
16,Ztti6dnZXPk,2021-02-03,5 Shihtzu Puppies 🐾 | 86 days old,800,28,4
17,6Gq6wWb7GU4,2021-01-28,5 Shihtzu Puppies 🐾 | Eating Strawberries 🍓,387,22,5
18,N7mV8bG0Zfo,2021-01-22,5 Shihtzu Puppies 🐾 | Enjoying Dog Snacks that...,316,15,5
19,114hdHiGI5Q,2021-01-20,5 Shihtzu Puppies 🐾 | 73 days old (part 2),2086,82,6
20,t9O35wK5_nA,2021-01-20,5 Shihtzu Puppies 🐾 | 73 days old,1084,47,6
21,SphRcIsWMLU,2021-01-20,5 Shihtzu Puppies 🐾| Taking Coatshine Syrup | ...,13762,71,25
22,WHSjAd_titk,2021-01-18,Shihtzu 🐾 | Tweedle the Mama/Nanay Dog is Eati...,364,26,2
23,XDM6odwAj1k,2021-01-17,5 Shihtzu Puppies 🐾 | 5th Visit to the Veterin...,796,21,6
24,uzUbZpndzPM,2021-01-15,5 Shihtzu Puppies 🐾😁 | ft. Human Size Teddy Be...,35677,1315,28
25,WpPZDUPyt5E,2021-01-15,5 Shihtzu Puppies 🐾❤️ | Eating Banana 🍌 (part 2),243,16,3
26,vyuIOw84KsI,2021-01-15,5 Shihtzu Puppies 🐾❤️ | Eating Banana 🍌,471,17,3
27,tIhQyFUO1R8,2021-01-14,Shihtzu Puppies 🐾😁 | 67 days old (part 2),217,12,3
28,mdllH634jiU,2021-01-14,Shihtzu Puppies 🐾 😁 | 67 days old,323,21,1
29,r2ZlOEYohRA,2021-01-10,Shihtzu | Tweedle the Mama Dog ❤️🐾,1757,74,6
30,9xiaBnLBePs,2021-01-08,Shih tzu Puppy 🐾 | Mickey is Playing Toy Eggs ❤️,252,14,3
31,4RMi8hamiQA,2021-01-07,2 Months old Shihtzu Puppies ♥️,3960,179,7
32,6mSTkyEIXIw,2021-01-07,5 Shihtzu Puppies | 2 Months Old,461,28,6
33,MkGQ3_jea-M,2021-01-07,5 Shihtzu Puppies taking Multivitamins,991,27,2
34,xiq8FlVj5Bk,2021-01-06,"I have 2 Pups, the left and the right 😁",139,15,1
35,GUekoXvUMHo,2021-01-05,Mickey wants to play with Goofy | Shihtzu puppies,565,28,1
36,kyT9BaeSIYo,2021-01-05,Shihtzu Puppies 🐾 | Extra Large Rawhide for t...,1864,70,1
37,gvy6Flwx0og,2021-01-04,Shih tzu puppies 🐾 | 58 days old,3953,133,8
38,VYF7yAappZ4,2021-01-03,Very Tender Marinade for Barbecue BBQ,57,8,0
39,jD2A0Q3Eb0Y,2021-01-03,Shih tzu puppies 🐾 | 57 days old (part 3),742,39,2
40,aEHaBPUdDZo,2021-01-03,Shih tzu puppies 🐾 | 57 days old (part 2),1173,42,3
41,XbPmRDPEBz0,2021-01-03,Shih tzu puppies 🐾 | 57 days old,28122,753,19
42,qfb9VZBtClA,2021-01-02,Loaf bread PIZZA cooked in a PAN ft. pineapple...,63,7,0
43,t3vkh04S8mg,2021-01-02,Lechon Kawali | New Year Eve Edition,49,4,0
44,1ezCEfREGxM,2020-12-30,Pretty Tiny Teeth of a Shihtzu Puppy 🐾,3287,171,9
45,H-iN_ws1QkI,2020-12-30,Tiny Barks of Shih tzu puppy | Dewey the 4th p...,1075,43,1
46,EDe5qNIz8zI,2020-12-30,Shih tzu puppies 🐾 | 53 days old,704,29,4
47,nm8U8b2yTe0,2020-12-30,How to cut your Shih tzu finger nails using re...,2188,19,0
48,Splzs_mK1D4,2020-12-30,Nissin | Aka Tonkotsu Flavour | Demae Ramen 🍜 ...,7971,189,3
49,Atl8ZoDmsuY,2020-12-30,"Samyang Carbonara with extras | Bacon 🥓 , Soft...",3144,93,1